# Generated by Django 5.2.4 on 2025-08-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_register_created_at_register_email_register_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='photo',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
